# .pre-commit-config.yaml
repos:
  -   repo: https://github.com/DubbelF34140/task-manager
      rev: v4.5.0
      hooks:
        -   id: check-yaml          # Vérifie la syntaxe des fichiers YAML
        -   id: end-of-file-fixer   # S'assure que les fichiers finissent par une ligne vide
        -   id: trailing-whitespace # Supprime les espaces inutiles en fin de ligne

  -   repo: https://github.com/DubbelF34140/task-manager
      rev: v0.1.6
      hooks:
        # Linter (détecte les erreurs, variables inutilisées, etc.)
        - id: ruff
          args: [ --fix ]
        # Formatter (range le code automatiquement selon les standards)
        - id: ruff-format